### ISSUE TITLE
don't have a scRNA reference

### ISSUE THREAD

**Issue by zhumengyan** [jdekanter/CHETAH#1]
Thank you for providing such a great tool for scientific community.
I have a question. You say that reference is  important for cell type classification.
But until now, not all tumour have enough dataset with detailed cell type annotation. What should I do to prepare the reference?

**Comment by jdekanter** [comment]
I totally missed this comment. I'm sorry! I will make sure check regularly.

You're completely right, not all tumor entities have comprehensive datasets available. 
There are however still many options, which mainly depend on what kind of cell types you expect in your data. 
Infiltrating immune cell normally have a distinct enough pattern to used across different tumor entities. This is something I have tested extensively. Starting with e.g. the dataset mentioned in the vignette (https://figshare.com/s/aaf026376912366f81b6) can be useful.

If you expect many cells from the tissue in which the biopt is taken (e.g. brain cells in brain tumors), taking data from a different tumor that arose in the same tissue or from healthy tissue can be useful.

Maybe you can give some information on the entity/entities you are working on? Then I can answer in a bit more detail.

**Comment by jdekanter** [comment]
As I haven't heard from you, I'm closing this issue, but feel free to open it up again or open a new one when you have any more questions!
