### ISSUE TITLE
Can we get % of cell type in each sample?

### ISSUE THREAD

**Issue by boseb** [jdekanter/CHETAH#10]
Hi, 
Is it possible to get the percentage of each sample's expression in each inferred cell type  ?
For instance, can we get the percentage of "mel_cell1" sample's expression in CD4 T Cell type? Can we say this percentage of mel_cell1's expression contributes towards CD4 T 's expression?

If so, could you please guide me?  

Thanks
Bose

**Comment by jdekanter** [comment]
Dear boseb,

I've been away for half a year, sorry for the lack of an answer.
The question is probably not relevant for you anymore, but I'll try to answer it still. If this is not useful and you need additional information, please feel free to create a new issue.

If I understand correctly, with "the contribution of mel_cell1 towards CD4 T's expression", you mean how similar the expression of mel_cell1 is compared to CD4 T. CHETAH does not calculate this specifically as it selects different genes in each step of classification, based on the other cell types in the reference. 

A way to do this is as following, however, this is not always very accurate (therefore CHETAH was build using a reference tree). You need to calculate a mean expression per reference cell type, then take the genes (200-500) with the highest variance within the mean reference expression, and use these to correlate all input cells to the reference cells. Then you have a similarity of each input cell to the reference cell types.
