### ISSUE TITLE
coordinates will lose matrix form if just have one row data

### ISSUE THREAD

**Issue by xiebb123456** [jdekanter/CHETAH#11]
thanks for the good tools, 
the coordinates in  'CHETAHclassifier'  needs to change form 
'coordinates <- coordinates[coordinates[,2] != 0, ]' to
'coordinates <- coordinates[coordinates[,2] != 0, ,drop=F]'

**Comment by jdekanter** [comment]
I've made this chance (fi-na-ly) in version 1.12.1, which should become available on Bioconductor within the next few days.
