### ISSUE TITLE
PlotCHETA redD option not working

### ISSUE THREAD

**Issue by ericpanyc** [jdekanter/CHETAH#12]
Hello,

I'm using UMAP as non-linear dimensional reduction method. 
`reducedDimNames(input_VS4)

[1] "UMAP"`

However, when I PlotCHETA with redD = "UMAP", the plot still shows the x and y axis as tSNE.
![image](https://user-images.githubusercontent.com/54253195/84832578-6595b080-afe2-11ea-871f-57ecabb99cdf.png)

**Comment by jdekanter** [comment]
Hi Eric,

Thanks for using CHETAH. 
Thanks for your input and sorry for the inconvenience. I see that I've never made the x and y axis labels adjust to the name of the dimensional reduction. So, the plot actually shows the UMAP dimensions, but the labels are not correct. I will work on this and hopefully upload an new version of the packages with some additional fixes at the end of the week.

Best,
Jurrian

**Comment by jdekanter** [comment]
This has been adjusted in Bioconductor version 1.12.1.
