### ISSUE TITLE
Getting NodeXX as the predicted cell type.

### ISSUE THREAD

**Issue by abayegan** [jdekanter/CHETAH#15]
After running `CHETAHclassifier()` I get many predictions with the format of `Node1,..., Node17` for many cells. I did not have such names for cell types in my reference data.

**Comment by jdekanter** [comment]
Hi abayegan,

Thanks for your question.
as you can read in the vignette, CHETAH classifies by using a tree of your reference cell types. 
For each cell, it will from top to bottom at each split in the tree if a cell belongs to the right or left branch. 
If there is not enough evidence to assign a cell to a specific branch, classification for that cell, will stop in that part of the tree, or that "node" of the tree. This prevents overclassification. 
You can nicely visualize this using the PlotCHETAH(chetah_output, interm = T, tree = T) function. This colors al "NodeX" cells and shows in which part of the tree they belong. 

If you would like to prevent this at all, you can use the
classify_all = Classify(chetah_output, 0).
This will classify all cells to a specific cell type. Watch out though, a lot of cells might become misclassified!

Hope this helped your question

**Comment by abayegan** [comment]
> Hi abayegan,
> 
> Thanks for your question. as you can read in the vignette, CHETAH classifies by using a tree of your reference cell types. For each cell, it will from top to bottom at each split in the tree if a cell belongs to the right or left branch. If there is not enough evidence to assign a cell to a specific branch, classification for that cell, will stop in that part of the tree, or that "node" of the tree. This prevents overclassification. You can nicely visualize this using the PlotCHETAH(chetah_output, interm = T, tree = T) function. This colors al "NodeX" cells and shows in which part of the tree they belong.
> 
> If you would like to prevent this at all, you can use the classify_all = Classify(chetah_output, 0). This will classify all cells to a specific cell type. Watch out though, a lot of cells might become misclassified!
> 
> Hope this helped your question

Thanks very much for the prompt response and the clarification.
