### ISSUE TITLE
unable to instal CHETAH with BioCManager version 3.15

### ISSUE THREAD

**Issue by Rohit-Satyam** [jdekanter/CHETAH#18]
Dear Developer

I am unable to install your package from BioConductor. I am getting the following error:

```r

> BiocManager::install("CHETAH")
'getOption("repos")' replaces Bioconductor standard repositories, see
'?repositories' for details

replacement repositories:
    CRAN: https://cloud.r-project.org

Bioconductor version 3.15 (BiocManager 1.30.18), R 4.2.1 (2022-06-23)
Installing package(s) 'CHETAH'
Installation paths not writeable, unable to update packages
  path: /usr/lib/R/library
  packages:
    nlme, spatial, survival
Warning message:
package ‘CHETAH’ is not available for Bioconductor version '3.15'

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
```

I temporarily used `devtools::install_github("jdekanter/CHETAH")` but you might want to look into it!!

**Comment by jdekanter** [comment]
Hi Rohit.

Thanks for letting me know. 
I was recently made aware that CHETAH failed builds in Bioconductor and was therefore deprecated (as I missed many messages from the bioc. maintainers.)
I've just now pushed changes that should resolve the issues to Bioconductor, so hopefully CHETAH will be available again soon.

Best,
Jurrian

**Comment by jdekanter** [comment]
Hi,

small update: CHETAH is building and checking "OK" on all platforms on Bioconductor. The maintainers are making it available again, which should be done within the next few days.

Best,
Jurrian
