### ISSUE TITLE
Questions about confidence score

### ISSUE THREAD

**Issue by Kevis9** [jdekanter/CHETAH#19]
Hi, thanks for the insightful work! Now I am using CHETAH to annotate query data based on reference data. I wonder how to get the confidence score of the predicted cell type.

Following is my core code:
```
input <- SingleCellExperiment(assays = list(counts = query_data))
input <- CHETAHclassifier(input = input, ref_cells = reference)
## Extract celltypes:
pred <- input$celltype_CHETAH
```

**Comment by jdekanter** [comment]
Hi Kevis9!

Thank you for using the tool!
The confidence scores are accessed via the internal colData.
That is stored here:
`pred@int_colData$CHETAH$conf_scores$Node0`
Or an alternative way of coding the same thing:
`int_colData(pred)$CHETAH$conf_scores$Node0`
The names of the nodes are the same as the nodes in the tree of PlotCHETAH().
I hope this answers your question. Feel free to open the question if you have additional questions.
