### ISSUE TITLE
Chetah reference data

### ISSUE THREAD

**Issue by royfrancis** [jdekanter/CHETAH#2]
Hi, Where can I access the reference data for Chetah (multiple cells per type)?
In addition, I was told about the availability of a Chetah reference data modified for use by SingleR (averaged single cell per type). I am unable to find this file. I was wondering if you know anything about this?
Thanks :)

**Comment by jdekanter** [comment]
Hey royfrancis,
Thanks for your question.

The standard reference data for CHETAH, made from tumor micro-environment data sets can be found here:
https://figshare.com/s/aaf026376912366f81b6

SingleR itself has a great reference datasets build into it, that are accessible by 
data("blueprint_encode") and data("hpca"). Those are very comprehensive and are optimized for that program. 

You can of course download the CHETAH reference and take an average per cell type from that reference to use for SingleR. That could be useful when applying it on tumor data, but in that case I would just recommend using CHETAH, or SingleR with its own reference. If you want to average the CHETAH reference and need the code for that, or when you have any other questions: just let me know!

**Comment by royfrancis** [comment]
Ok. I've been able to get it to work. Thanks! The tool works well and fast. I just need to get better reference data.
Just a comment: You have a nice and informative vignette.  It would be great if you could just add the rendered version of the vignette here somewhere in the repo. That would be convenient for people who are curious to see the capabilities of this package before installing it and rendering the vignette.

**Comment by jdekanter** [comment]
Thanks for your comment, and great that you like the tool. Making a more elaborate set of references available is still on my to do list, but will take some time. I will add the html vignette here as well, good comment. Deleted it when submitting to Bioconductor, but never thought about adding it back in on this repo.
