### ISSUE TITLE
Error in running ClassifyReference and CorrelateReference

### ISSUE THREAD

**Issue by liorlobel** [jdekanter/CHETAH#3]
Hi, first of all congrats on a well done paper and a highly needed tool :) 
I'm new to the field and I'm trying to use CHETAH with mouse data. I'm trying to generate a reference classifier utilizing the Tabula Muris data. I have 23,330 genes across 6059 cells in the reference dataset.  I think I managed to generate the SingleCellExpriment object correctly. 
When I run the QC analyses I get: 
`"Error in ref_profiles[, type, drop = FALSE] : subscript out of bounds"`

My code: 

```
#### Loading Tabula Muris counts and metadata

expTMraw<-utils_loadObject("~/Downloads/expMatrix_TM_Raw_Oct_12_2018.rda")
stTM<-utils_loadObject("~/Downloads/sampTab_TM_053018.rda")

##### Generating the SingleCellExperiment object
tabula_ref <- SingleCellExperiment(assays = list(counts = expTMraw),
                                     colData = DataFrame(celltypes = stTM$cell_ontology_class))

##### Selecting 200 cells at most for each celltype
cell_selection <- unlist(lapply(unique(tabula_ref$celltypes), function(type) {
    type_cells <- which(tabula_ref$celltypes == type)
    if (length(type_cells) > 200) {
        type_cells[sample(length(type_cells), 200)]
    } else type_cells
}))
ref_new <- tabula_ref[ ,cell_selection]

##### Normalize the ref data
assay(ref_new, "counts") <- apply(assay(ref_new, "counts"), 2, function(column) log2((column/sum(column) * 100000) + 1))

##### Adapting the ribo table for mouse genes
ribo <- read.table("~/Downloads/ribosomal.txt", header = FALSE, sep = '\t')
ribo$V1=sapply(ribo$V1, FUN = tolower)
ribo$V1=sapply(ribo$V1, FUN = firstup)
ref_new <- ref_new[!rownames(ref_new) %in% ribo[,1], ]

##### QC analyses of the classifier
ClassifyReference(ref_cells = ref_new, ref_c = "counts")
```

Running the QC functions on the headneck_ref works fine. 

Will be grateful for any advice, 
Thanks, 
Lior

**Comment by liorlobel** [comment]
Managed to debug! The problem was that one of the celltypes levels was an empty string, I'm guessing a non-defined cell type, so I changed it to non-defined and it works. 

:) 
![image](https://user-images.githubusercontent.com/8280386/61567443-8f023100-aa4d-11e9-8b3c-7bf2db31bacf.png)

**Comment by jdekanter** [comment]
Thanks for the interest. 
And perfect! Was just trying to recreate the problem here.
Will soon add a specific error message for this. Every Tabula Muris dataset has such an empty category if I remember correctly, so maybe more people will run into this problem.
You result looks quite good by the way, hope it will also work nicely on your target data!
