### ISSUE TITLE
plotCHETAH 

### ISSUE THREAD

**Issue by liorlobel** [jdekanter/CHETAH#4]
Hi again, 
I get an error when running plotCHETAH - 
`Error in names(gray) <- int_nodes : 
  'names' attribute [38] must be the same length as the vector [23]`

I think it's related to the following code:

```
M <- max(length(int_nodes), length(leaf_nodes))
        if (length(M) < 24)   {
            gray <- paste0('gray', rev(seq(2, 92, 4)))
        } else if (length(M) < 47) {
            gray <- paste0('gray', rev(seq(2, 92, 2)))
        } else {
            gray <- rep('gray70', M)
        }
```
M stores the max length of the nodes, but its length is always 1, therefore the if statement M<24 is always true.. I have 38 classifications so that's why I get the error. I suggest comparing M and not length(M). 

Hope this makes sense :), 

Thanks, 
Lior

**Comment by jdekanter** [comment]
Hey, 

Thanks for diving into the code, you identified the problem correctly. This is really stupid. I encountered the mistake myself before and fixed it, but apparently forgot to add the changes to Bioconductor. 

Fixed it in the new release (1.0.4), or when that's not build yet, you can use the version here on Github. 
I also incorporated the warning message from your previous issue.

Thanks for all the feedback! It is very welcome :)

**Comment by royfrancis** [comment]
I wonder if this is related. I get `Warning: Error in grDevices::rainbow: object 'M' not found` for some of the plots when running `CHETAHshiny(sce2)`. It seems be fine with the confidence plot and `PlotCHETAH(sce2)`.

**Comment by jdekanter** [comment]
Hey royfrancis,
I cannot recreate the problem you have. 
I guess it might have to do with the same problem, although "not found" is a bit weird, as "M" should always be defined. Which version are you running? If not the latest, try to update to CHETAH 1.0.4., this might solve your problem
