### ISSUE TITLE
Confidence plot

### ISSUE THREAD

**Issue by royfrancis** [jdekanter/CHETAH#5]
Is there a function to plot the confidence plot shown in the shiny app? And how can I get the confidence scores out of the SCE object? Is there an accessor or can I get it from one of the slots?

**Comment by jdekanter** [comment]
Hey! 
Both the confidence plot and accessor function(s) are a good idea. Will implement that as soon as possible.

In the mean time: 
To assess the confidence score, do:
`sce@int_colData$CHETAH$conf_scores `
The nodes are named, as according to the Node names in the Classification tree. 
Each node holds a matrix with a column for each cell type in that node.
So, as to access the "Fibroblast" confidence score in Node3, do:
`FibrNode3 <- sce@int_colData$CHETAH$conf_scores$Node3$Fibroblast.`
To plot these, do:
`PlotTSNE(toplot = FibrNode3, input = sce)`
